"""add task group_name and is_routine

Revision ID: 14b481df1b5d
Revises: 4b810efba1fc
Create Date: 2026-07-26 00:38:13.439613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b481df1b5d'
down_revision = '4b810efba1fc'
branch_labels = None
depends_on = None


def upgrade():
    # server_default so existing rows satisfy NOT NULL (autogenerate omits it).
    # One batch block PER column: when the batch recreates the table (which
    # happens on legacy-adopted databases), two added columns in one block
    # give Alembic's column-reordering a cycle and the upgrade dies.
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=60), nullable=True))
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_routine', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_routine')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
