"""add user.visit_access

Revision ID: 4225ca785d1b
Revises: c5a91e2f70b4
Create Date: 2026-08-12 00:13:12.485103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4225ca785d1b'
down_revision = 'c5a91e2f70b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_access', sa.String(length=16), server_default='friends', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('visit_access')

    # ### end Alembic commands ###
