import { DEFAULT_CHARACTER, validateCharacter } from "./profile.js";

// Complete, editable starting looks. Every preset carries every character
// field so applying one never leaks a hat, pattern, or body slider from the
// previous outfit. Skin is the deliberate exception at APPLICATION time:
// it belongs to the person, not the clothes, so characterFromPreset replaces
// the baseline value with the user's current selection.
const look = (key, label, tagline, character) => ({
  key,
  label,
  tagline,
  character: validateCharacter({ ...DEFAULT_CHARACTER, ...character }),
});

export const CHARACTER_PRESETS = [
  look("fall-girl", "Fall style girl", "Warm knits · boots", {
    model: "fem",
    hair: "long",
    hairColor: "#8c4a2f",
    garment: "turtleneck",
    outfit: "#c9a24b",
    coat: "cardigan",
    coatColor: "#4e6b4a",
    pants: "skirt",
    trouser: "#8a5a44",
    shoes: "boots",
    shoeColor: "#5b3a29",
    scarf: "long",
    scarfColor: "#8e3a3f",
    expression: "happy",
    width: 6.4,
    shoulders: -1.0,
    height: 30.5,
    torso: 16.5,
  }),
  look("fall-guy", "Fall style guy", "Plaid layers · denim", {
    model: "masc",
    hair: "curtains",
    hairColor: "#5b3a29",
    garment: "shirt",
    outfit: "#c8b394",
    inner: "#8a5346",
    print: "plaid",
    coat: "jacket",
    coatColor: "#8a5a44",
    pants: "jeans",
    trouser: "#3f5a7a",
    shoes: "boots",
    shoeColor: "#5b3a29",
    scarf: "loop",
    scarfColor: "#c9a24b",
    expression: "calm",
    width: 6.7,
    shoulders: -1.0,
    height: 32.5,
    torso: 17,
  }),
  look("school-girl", "School girl", "Blazer · pleated skirt", {
    model: "fem",
    hair: "bob",
    hairColor: "#3a3142",
    garment: "blouse",
    outfit: "#f2e9dd",
    inner: "#8e3a3f",
    coat: "blazer",
    coatColor: "#3f5a7a",
    pants: "pleats",
    trouser: "#3a3a42",
    shoes: "maryjanes",
    shoeColor: "#26232b",
    expression: "happy",
    width: 6.3,
    shoulders: -1.2,
    height: 29.5,
    torso: 16,
  }),
  look("school-boy", "School boy", "Tie · tailored blazer", {
    model: "masc",
    hair: "twoblock",
    hairColor: "#3a3142",
    garment: "tie",
    outfit: "#f2e9dd",
    inner: "#8e3a3f",
    coat: "blazer",
    coatColor: "#3f5a7a",
    pants: "dress",
    trouser: "#3a3a42",
    shoes: "loafers",
    shoeColor: "#26232b",
    expression: "calm",
    width: 6.5,
    shoulders: -1.1,
    height: 31,
    torso: 16.5,
  }),
  look("office-female", "Office wear female", "Soft blouse · tailoring", {
    model: "fem",
    hair: "bun",
    hairColor: "#3a3142",
    garment: "blouse",
    outfit: "#e9dcc9",
    inner: "#c4767f",
    coat: "blazer",
    coatColor: "#4a3a5b",
    pants: "dress",
    trouser: "#3a3a42",
    shoes: "heels",
    shoeColor: "#26232b",
    glasses: "halfmoon",
    expression: "calm",
    width: 6.5,
    shoulders: -0.8,
    height: 33,
    torso: 17.5,
  }),
  look("office-male", "Office wear male", "Crisp shirt · suit", {
    model: "masc",
    hair: "short",
    hairColor: "#3a3142",
    garment: "tie",
    outfit: "#d8e1e8",
    inner: "#c9a24b",
    coat: "blazer",
    coatColor: "#3a3a42",
    pants: "dress",
    trouser: "#3a3a42",
    shoes: "loafers",
    shoeColor: "#5b3a29",
    expression: "calm",
    width: 6.8,
    shoulders: -0.8,
    height: 33.5,
    torso: 17.5,
  }),
  look("lofi-girl", "Lofi girl", "Headphones · roomy layers", {
    model: "fem",
    hair: "highpony",
    hairColor: "#5b3a29",
    garment: "sweater",
    outfit: "#c4767f",
    coat: "cardigan",
    coatColor: "#8a5346",
    pants: "wide",
    trouser: "#3f5a7a",
    shoes: "sneakers",
    shoeColor: "#d9cbb2",
    hat: "headphones",
    glasses: "round",
    expression: "calm",
    width: 6.4,
    shoulders: -1.1,
    height: 30.5,
    torso: 17,
  }),
  look("cozy-gamer", "Cozy gamer", "Hoodie · headphones", {
    model: "masc",
    hair: "messy",
    hairColor: "#3a3142",
    garment: "tee",
    outfit: "#e9dcc9",
    coat: "hoodie",
    coatColor: "#6b4a6e",
    pants: "joggers",
    trouser: "#3a3a42",
    shoes: "sneakers",
    shoeColor: "#26232b",
    hat: "headphones",
    expression: "happy",
    width: 6.6,
    shoulders: -1.2,
    height: 30,
    torso: 17.5,
  }),
];

const CHARACTER_FIELDS = Object.keys(DEFAULT_CHARACTER);
const STYLE_FIELDS = CHARACTER_FIELDS.filter((key) => key !== "skin");

/** Materialize a look without ever replacing the user's selected skin. */
export function characterFromPreset(preset, skin) {
  if (!preset?.character) return null;
  return validateCharacter({ ...preset.character, skin });
}

export function characterPresetMatches(character, preset) {
  if (!preset?.character) return false;
  return STYLE_FIELDS.every((key) => character?.[key] === preset.character[key]);
}
